### PR TITLE
Inactivity timer for OOP plugins

### PR DESCRIPTION
**Pull request by monich**
Plugin process will exit if it's not doing anything for too long.

### CODE REVIEW

**Comment by chriadam** [comment]
LGTM except I wonder if there are some plugins which need to stay alive to listen for incoming connections (eg, the SyncML server plugin which handles incoming bluetooth obex requests, may be like that).

If this patch only affects client plugins, and not server plugins, then to me it looks fine, I think.

@blammit @hmallat any comments?

**Comment by chriadam** [comment]
See eg https://github.com/nemomobile/buteo-sync-plugins/blob/master/serverplugins/syncmlserver/syncmlserver.pro

**Comment by monich** [comment]
I'm wondering then if this fairly trivial piece of code is worth sharing between plugins, especially in such a weird way.

**Comment by monich** [comment]
For the record, with the current approach the system doesn't recover from msyncd crash if the plugins were running when it crashed. Plugins keep running after msyncd restart, new instances launched by msyncd fail to register with D-Bus => nothing works.

**Comment by monich** [comment]
Another solution for the "stuck client" problem would be for msyncd to kill the leftovers.

**Comment by amtep** [comment]
Could we delegate the starting and killing of plugins to systemd perhaps?

**Comment by monich** [comment]
How about this: https://github.com/nemomobile/buteo-syncfw/pull/83

**Comment by monich** [comment]
Closing this one, will merge https://github.com/nemomobile/buteo-syncfw/pull/82 instead.

**Pull request closed without merging**
